name: Radarr 4K
version: 0.5.0
slug: radarr4k
description: Movie organizer/manager for usenet and torrent users
url: https://github.com/hassio-addons/addon-radarr/tree/main/README.md
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:7879]
init: false
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  7879/tcp: 7879
image: ghcr.io/hassio-addons/radarr/{arch}
