name: Sonarr 4K
version: 0.1.4
slug: sonarr4k
description: Smart PVR for newsgroup and bittorrent users
url: https://github.com/hassio-addons/addon-sonarr/tree/main/README.md
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:18989]
init: false
arch:
- aarch64
- amd64
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  18989/tcp: 18989
image: ghcr.io/hassio-addons/sonarr/{arch}
