name: Notifiarr
version: "0.7.0"
slug: notifiarr
description: This is the unified client for Notifiarr.com. The client enables content requests from Media Bot in your Discord Server and also provides reports for Plex usage and system health among many other features
url: "https://github.com/Notifiarr/notifiarr"
image: golift/notifiarr
startup: application
init: false
webui: http://[HOST]:[PORT:5454]
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - share:rw
  - config:rw
  - addon_config:rw
ports:
  5454/tcp: 5454
ports_description:
  5454/tcp: Web Interface
host_network: false
